---
title: "ICD-10 Look-Up"
author: "Daniel P. Hall Riggins, MD"
date: "8/26/2021"
output: html_document
---

Load needed libraries:

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(httr)
```
```{r}
response <- GET("http://icd10api.com/?code=O21.9&desc=long&r=json")
response
```

Define function taking an ICD code as input and returning the description of that code using an API webservice:

```{r}
ICD_description_API <- function(icd_code) {
    # Construct URL to send to the API
    url <- paste0("http://icd10api.com/?code=",icd_code,"&desc=long&r=json")
    # Send the URL and collect response
    response <- GET(url)
    # Parse the response into an R native object
    parsed_object <- jsonlite::fromJSON(
        content(
            response,
            as = "text"
        ), 
        simplifyVector = FALSE
    )
    # Fill in NULL reponses with NA
    if(
        is.null(parsed_object$Description)
    ){
        return(NA)
    # Otherwise return the parsed description
    } else {
        return(parsed_object$Description)
    }
}

```

Load a table of all unique ICD-10 codes extracted from the dataset "AllVisitsStroger2020toPresent.csv" (leaving out identifiers):

```{r}
test_codes <- read_csv("ICD_codes.csv")

test_codes
```

Test out the function on our table:

```{r}
test_codes %>%
    rowwise() %>%
    mutate(
        description = ICD_description_API(ICD_10_code)
    )
    
```

```{r}

```

