---
title: "mrc_referrals"
author: "Daniel P. Hall Riggins, MD"
date: "10/21/2021"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
all_raw <- read_csv("data/MRC_ALL_DATA_LABELS_2021-09-30_1556.csv")
```

Total months of operations:

```{r}
start_date <- as_date("2020-12-08") # From date of communication in 2nd record
date_of_export <- as_date("2021-09-30") # From time-stamp on data file
operation_months <- start_date %--% date_of_export / dmonths(1)
operation_months
```

To get total referrals (174), get the max number for client ID:

```{r}
max(all_raw$`Record ID`)
```

Summarize referral sources:

```{r}
referrals <- all_raw %>%
    select(
        record = `Record ID`, 
        referrer = `Referring Organization`,
        primary_cat = `Primary Referral Category`,
        disposition = `Disposition?`
    ) %>%
    filter(
        !is.na(referrer) | !is.na(primary_cat) | !is.na(disposition)
    ) %>%
    mutate(
        referrer = as_factor(referrer),
        primary_cat = as_factor(primary_cat),
        disposition = as_factor(disposition),
        
    )

referrers <- referrals %>%
    group_by(referrer) %>%
    summarize(count = n()) %>%
    mutate(
        percent = (count/174*100),
        variable = "referral_source"
    )

dispo_cat_totals <- referrals %>%
    group_by(
        disposition
    ) %>%
    summarize(
        cat_total = n()
    ) 

referral_summary <- referrals %>%
    group_by(
        primary_cat,
        disposition
    ) %>%
    summarize(
        count = n()
    ) %>%
    full_join(
        dispo_cat_totals
    ) %>%
    mutate(
        percent = count/cat_total*100,
        variable = "referral_cat_by_dispo"
    )
```

```{r}

```

