---
title: "1 Prepping Datasets for Deduplication"
author: "Daniel P. Hall Riggins, MD"
date: "9/11/2021"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(arrow)
library(readxl)
library(tidyverse)
```

```{r message=FALSE, warning=FALSE}
FHP_raw <- read_xlsx(
    "mrc_data/FHPMatchedtoEMRMatchedtoChante_reduced.xlsx",
    sheet = "EncounterdatawithChante",
    na = "NULL"
)

deaths_raw <- read_xlsx(
    "mrc_data/MatchingtoMEdata.xlsx", 
    na = "NULL"
)

claims_raw <- read_xlsx(
    "mrc_data/Rectified_FHSP_CC_20201102.xlsx",
    col_types = c("numeric", "text")
)

alerts_raw <- read_xlsx(
    "mrc_data/20201023AlertList.xlsx"
)

casework_raw <- read_xlsx(
    "mrc_data/Unencrypted_CCHreport.xlsx",
    na = "NA"
)
```

```{r functions}
dedupe_prep <- function(source, columns, origin) {
    print(
        paste0(
            "Initial number of records is ",
            nrow(source)
        )
    )
    distinct1 <- distinct(source)
    print(
        paste0(
            "Which reduces to ",
            nrow(distinct1),
            " when disinct() is first run"
        )
    )
    select2 <- select({{distinct1}}, {{columns}})
    distinct3 <- distinct(select2)
    print(
        paste0(
            "Which reduces to ",
            nrow(distinct3),
            " when disinct() is run after selecting columns of interest"
        )
    )
    return(distinct3)
}

make_duplicate_ref <- function(source, variable) {
    reference <- source %>%
    group_by({{variable}}) %>%
    summarize(n = n()) %>%
    filter(n > 1) %>%
    filter(!is.na({{variable}}))
}
```


```{r FHP people prep}
FHP_people <- dedupe_prep(
    source = FHP_raw,
    columns = c(person_id, cmrn_id, rin_cc, NAME_FIRST, NAME_LAST, BIRTH_DT_TM, sex_cd, race, ethnicity)
    ) %>%
    mutate(
        first_name = str_to_title(NAME_FIRST),
        last_name = str_to_title(NAME_LAST)
    ) %>%
    mutate(
        name = paste0(first_name, " ", last_name)
    ) %>%
    rename(
        dob = BIRTH_DT_TM
    ) %>%
    select(
        -c(NAME_FIRST, NAME_LAST, first_name, last_name)
    ) %>%
    rename_with(
        ~ paste0(.x, ".fhp")
    )
```
```{r}
deaths_people <- dedupe_prep(
    source = deaths_raw,
    columns = everything()
    ) %>%
     mutate(
        first_name = str_to_title(DECEDENT_FIRST_NAME),
        last_name = str_to_title(DECEDENT_LAST_NAME)
    ) %>%
    mutate(
        name = paste0(first_name, " ", last_name)
    ) %>% 
    rename(
        dob = DECEDENT_DOB,
        person_id = Person_ID,
        rin_cc = RIN_CC
    ) %>%
    select(
        -c(DECEDENT_FIRST_NAME, DECEDENT_LAST_NAME, first_name, last_name)
    ) %>%
    rename_with(
        ~ paste0(.x, ".deaths")
    )
```

```{r}
alerts_people_intermediate <- dedupe_prep(
    source = alerts_raw,
    columns = c(name, mrn, cmrn),
    origin = "20201023AlertList.xlsx"
    ) %>% 
    filter(
        !(is.na(name)) 
    ) %>% 
    mutate(
        name = str_to_title(name)
    ) 

alerts_split_name <- str_split_fixed(
    string = alerts_people_intermediate$name, 
    pattern = ", ",
    n = 2
)

alerts_people <- alerts_people_intermediate %>%
    mutate(
        name = paste0(alerts_split_name[,2], " ", alerts_split_name[,1])
    ) %>%
    rename(
        cmrn_id = cmrn
    ) %>%
    rename_with(
        ~ paste0(.x, ".alerts")
    )
```


```{r}
casework_people <- dedupe_prep(
    source = casework_raw,
    columns = c("Client ID", "Legacy ID", "Client Name"),
    origin = "Unencrypted_CCHreport.xlsx"
) %>%
    rename(
        name = "Client Name"
    ) %>%
    rename_with(
        ~ paste0(.x, ".casework")
    )
```

```{r}
people <- FHP_people %>%
    full_join(
        deaths_people,
        by = c(
            "name.fhp" = "name.deaths", 
            "dob.fhp" = "dob.deaths"
        ),
        suffix = c("", "")
    ) %>%
    full_join(
        alerts_people,
        by = c(
            "name.fhp" = "name.alerts",
            "cmrn_id.fhp" = "cmrn_id.alerts" 
        )
    ) %>%
    full_join(
        casework_people,
        by = c("name.fhp" = "name.casework")
    )

dup_name_ref <- make_duplicate_ref(people, name.fhp)
dup_cmrn_ref <- make_duplicate_ref(people, cmrn_id.fhp)
dup_rin_ref <- make_duplicate_ref(people, rin_cc.fhp)
dup_personid_ref <- make_duplicate_ref(people, person_id.fhp)
dup_dob_ref <- make_duplicate_ref(people, dob.fhp)


all_possible_dups <- people %>%
    filter(
        (name.fhp %in% dup_name_ref$name.fhp) | 
        (cmrn_id.fhp %in% dup_cmrn_ref$cmrn_id.fhp) |
        (rin_cc.fhp %in% dup_rin_ref$rin_cc.fhp) |
        (person_id.fhp %in% dup_personid_ref$person_id.fhp) |
        (dob.fhp %in% dup_dob_ref$dob.fhp)
    )
```





```{r}

history_encounters <- history_raw %>%
    # 145490 observations
    #distinct() %>%
    # No change
    select(
        !c(BIRTH_DT_TM, sex_cd, race, ethnicity)
    ) %>%
    #distinct() %>%
    # No change
    mutate(
        origin = "encounter_history.xlsx"
    )

FHP_encounters <- FHP_raw %>%
    # 86576 rows
    distinct() %>%
    # 44346 rows
    select(
        !c(NAME_FIRST, NAME_LAST, BIRTH_DT_TM, sex_cd, race, ethnicity)
    ) %>%
    #distinct() %>%
    # no change
    mutate(
        origin = "FHPMatchedtoEMRMatchedtoChante_reduced.xlsx"
    )


```






