---
title: "Prepping variables for MRC Mortality Analysis"
author: "Daniel P. Hall Riggins, MD"
date: "10/5/2021"
output: html_document
---

```{r}
library(arrow)
library(tidyverse)
library(lubridate)
library(xlsx)
```

```{r}
all_raw <- read_csv("data/MRC_ALL_DATA_LABELS_2021-09-30_1556.csv")
```

```{r}
people_prep <- function(source, columns) {
    print(
        paste0(
            "Initial number of records is ",
            nrow(source)
        )
    )
    distinct1 <- distinct(source)
    print(
        paste0(
            "Which reduces to ",
            nrow(distinct1),
            " when filtering for distinct rows"
        )
    )
    select2 <- select({{distinct1}}, {{columns}})
    distinct3 <- distinct(select2)
    print(
        paste0(
            "Which reduces to ",
            nrow(distinct3),
            " when filtering for distinct rows after selecting columns of interest"
        )
    ) 
    filter4 <- filter(
        distinct3,
        distinct3$disposition %in% "Accepted" & 
            !(is.na(distinct3$last_name))
    )
    print(
        paste0(
            "Which reduces to ",
            nrow(filter4),
            " when filtering for accepted clients"
        )
    ) 
    return(filter4)
}
```

```{r}
people_columns <- c(
    mrc_id = "Record ID", 
    last_name = "Client Last Name...55", 
    first_name = "Client First Name...56", 
    other_name = "Client Other name", 
    dob = "Client DOB...58", 
    sex = "Sex", 
    black = "What is your race? (choice=Black)", 
    white = "What is your race? (choice=White)",
    asian = "What is your race? (choice=Asian/American Indian or Alaska native)",
    pacific = "What is your race? (choice=Native Hawaiian or Pacific Islander)",
    multiracial = "What is your race? (choice=Multiracial)",
    other_race = "What is your race? (choice=Other)",
    hispanic = "Do you consider yourself Hispanic or Latinx?",
    mental_condition = "Do You have any mental health condition",
    hallucinations = "Do you hear voices or see things that others might not see?",
    hospitalized = "Have you ever been hospitalized for psychiatric or substance use conditions?",
    heroin_fentanyl = "heroin or fentanyl",
    pain_pills = "pain pills not prescribed to you",
    methadone = "methadone",
    bupe = "buprenorphine (Suboxone)",
    OUD_program = "Are you dispensed (methadone/burprenorphine) as part of a program?",
    alcohol_disorder = "Have you been hospitalized for dangerous alcohol withdrawal, had withdrawal seizures or hallucinations, or delirium tremens?",
    other_drugs = "Do you take any other street drugs?",
    referral_cat = "Primary Referral Category",
    care_need = "What is the care need?",
    insurance_cat = "What insurance do you have?",
    disposition = "Disposition?"
)
```

```{r}
mrc_just_people <- people_prep(all_raw, people_columns)
```

```{r}
mrc_people_admDate <- all_raw %>%
    select(
        mrc_id = "Record ID",
        mrc_admission_date = "MI1:Registration Date"
    ) %>%
    filter(mrc_id %in% mrc_people$mrc_id) %>%
    group_by(mrc_id) %>%
    summarize(mrc_admission_date = first(mrc_admission_date)) %>%
    full_join(mrc_just_people)
```
```{r}
mrc_people_admDate_dischDate <- all_raw %>%
    select(
        mrc_id = "Record ID",
        mrc_discharge_date = "Discharge Date"
    ) %>%
    filter(
        mrc_id %in% mrc_people$mrc_id &
            !is.na(mrc_discharge_date)
    ) %>%
    group_by(mrc_id) %>%
    summarize(mrc_discharge_date = max(mrc_discharge_date)) %>%
    full_join(mrc_people_admDate)
```

```{r}
mrc_people <- mrc_discharge_dest <- all_raw %>%
    select(
        mrc_id = "Record ID",
        mrc_discharge_dest = "Discharge Destination"
    ) %>%
    filter(
        mrc_id %in% mrc_people$mrc_id &
            !is.na(mrc_discharge_dest)
    ) %>% 
    group_by(mrc_id) %>%
    summarize(mrc_discharge_dest = first(mrc_discharge_dest)) %>%
    full_join(mrc_people_admDate_dischDate)
```
Manual corrections:

```{r}
mrc_people[60,2] = "Unknown"
mrc_people[60,3] = as_date("2021-03-27")
mrc_people[61,2] = "Rush Oak Park ED"
mrc_people[61,3] = as_date("2021-03-12")
mrc_people[62,2] = "Unknown"
mrc_people[62,3] = as_date("2021-03-09")
mrc_people[64,2] = "Housing Forward"
mrc_people[64,3] = as_date("2021-04-30")
mrc_people[67,2] = "Unknown"
mrc_people[67,3] = as_date("2021-05-23")
mrc_people[68,2] = "Stroger Hospital"
mrc_people[68,3] = as_date("2021-07-03")
mrc_people[70,2] = "Unknown"
mrc_people[70,3] = as_date("2021-09-09")
mrc_people[73,2] = "Unknown"
mrc_people[73,3] = as_date("2021-08-22")
```


```{r}
mrc_discharge_dest %>%
    group_by(mrc_id) %>%
    summarise(n = n()) %>%
    filter(n > 1) %>%
    left_join(mrc_discharge_dest)

```


```{r}
write_parquet(mrc_people, "data/mrc_people_model/mrc_people.parquet")
```


```{r}
clustered_mrc_people_raw <- read_parquet("data/mrc_people_model/clustered_mrc_people.parquet")
```

```{r}
clustered_mrc_people <- clustered_mrc_people_raw %>%
    mutate(
        across(
            .cols = c(
                dob, 
                mrc_admission_date,
                mrc_discharge_date
            ),
            .fns = ~ ymd(.x)
        ),
        across(
            .cols = last_name:first_name,
            .fns = ~ str_to_title(.x)
        ),
        across(
            .cols = c(
                sex,
                referral_cat,
                insurance_cat,
                mrc_discharge_dest
            ),
            .fns = ~ as_factor(.x)
        ),
        across(
            .cols = black:alcohol_disorder,
            .fns = ~ case_when(
                .x %in% c("checked", "yes") ~ TRUE,
                .x %in% c("unchecked", "no") ~ FALSE
            )
        ),
        age = floor(dob %--% mrc_admission_date / dyears(1)),
        age_cat = factor(
            case_when(
                age < 25 ~ "0-24",
                age > 24 & age < 35 ~ "25-34",
                age > 34 & age < 45 ~ "35-44",
                age > 44 & age < 55 ~ "45-54",
                age > 54 & age < 65 ~ "55-64",
                age > 64 ~ "65+"
            ),
            ordered = TRUE,
            levels = c("0-24", "25-34", "35-44", "45-54", "55-64", "65+")
        ),
        mental_disorder = as_factor(
            case_when(
                mental_condition == TRUE |
                    hallucinations == TRUE ~ "Yes",
                hospitalized == TRUE ~ "Maybe"
            )
        ),
        substance_disorder = as_factor(
            case_when(
                heroin_fentanyl == TRUE |
                    pain_pills == TRUE |
                    methadone == TRUE |
                    bupe == TRUE |
                    OUD_program == TRUE |
                    alcohol_disorder == TRUE |
                    str_detect(
                        other_drugs,
                        "crack|marijuana|cocaine|heroin"
                    ) ~ "Yes",
                hospitalized == TRUE ~ "Maybe"
            )
        ),
        mrc_discharge_dest = str_to_lower(mrc_discharge_dest),
        discharge_dest_cat = as_factor(
            case_when(
                str_detect(
                    mrc_discharge_dest,
                    "bridge|sro|permanent|apartment|recovery|fillmore|transitional|greenwood|airport"
                ) ~ "Bridge/Stable Housing",
                str_detect(
                    mrc_discharge_dest,
                    "haymarket|rehab|(treatment center)|((?=.*h.a.s)(?=.*program))"
                ) ~ "Residential Treatment",
                str_detect(
                    mrc_discharge_dest,
                    "boulevard|julian"
                ) ~ "Interim/Emergency Housing, Chicago",
                str_detect(
                    mrc_discharge_dest,
                    "forward|((?=.*transfer)(?=.*room))|((?=.*shelter)(?=.*evanston))|rm|hf|((?=.*211)(?=.*fl))"
                ) ~ "Interim/Emergency Housing, Suburbs",
                str_detect(
                    mrc_discharge_dest,
                    "temporary|transfer|shelter"
                ) ~ "Interim/Emergency Housing, Unclear Region",
                str_detect(
                    mrc_discharge_dest,
                    "family|brother|sister|cousin|friend"
                ) ~ "Family/Friend/Other",
                str_detect(
                    mrc_discharge_dest,
                    "ltac|hospital|rush"
                ) ~ "ED/Hospital",
                str_detect(
                    mrc_discharge_dest,
                    "declined|abscond"
                ) ~ "Absconded/Without Plan",
                str_detect(
                    mrc_discharge_dest,
                    "home"
                ) ~ "Unclear",
                str_detect(
                    mrc_discharge_dest,
                    "unknown"
                ) ~ "Unknown"
            )
        )
    )
```

```{r}
count_and_percent <- function(tbl, var_name) {
    tbl %>%
    group_by(.data[[var_name]]) %>%
    summarize(count = n()) %>%
    mutate(
        variable = var_name,
        percent = round(
            (count/nrow(tbl)*100),
            digits = 2
        )
    ) %>%
    rename(
        category = .data[[var_name]]
    )
}
```

```{r}
columns <- c("sex", "black", "white", "asian", "pacific", "multiracial", "other_race", "hispanic", "referral_cat", "insurance_cat", "age_cat", "mental_disorder", "substance_disorder", "discharge_dest_cat")
summary_tables <- map(columns, ~count_and_percent(clustered_mrc_people, .x))
```


```{r}
purrr::map2(
    .x = summary_tables,
    .y = columns,
    .f = ~ xlsx::write.xlsx(
        x = .x,
        file = "data/mrc_summary_tables.xlsx",
        sheetName = .y,
        append = TRUE
    )
)
```


